apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: ananta-platform

  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 24.1.0
    chart: redis
    helm:
      releaseName: redis-argocd
      values: |
        fullnameOverride: redis-argocd
        architecture: standalone
        auth:
          enabled: true
          password: "argocdtest123"
        master:
          persistence:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: cache-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
