apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
spec:
  project: ananta-platform

  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.2.5
    chart: nginx
    helm:
      releaseName: nginx-demo
      values: |
        fullnameOverride: nginx-demo
        replicaCount: 2
        service:
          type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: ananta-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
