apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-local
  namespace: argocd
spec:
  project: ananta-platform

  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.2.1
    chart: postgresql
    helm:
      releaseName: postgresql
      values: |
        fullnameOverride: postgresql
        image:
          tag: 16
        auth:
          postgresPassword: "localdevpassword123"
          database: ananta
        primary:
          persistence:
            enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: database-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
