apiVersion: v2
name: tenant-management-service
description: ARC-SaaS Tenant Management Service Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - arc-saas
  - tenant-management
  - saas
  - multi-tenant
maintainers:
  - name: ARC-SaaS Team
dependencies: []
