apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin-app.fullname" . }}-nginx
  labels:
    {{- include "admin-app.labels" . | nindent 4 }}
data:
  default.conf: |
    {{- .Values.nginx.serverBlock | nindent 4 }}
