apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tenant-management-service.fullname" . }}
  labels:
    {{- include "tenant-management-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
