# Development environment overrides
api:
  replicaCount: 1
  autoscaling:
    enabled: false
  ingress:
    hosts:
      - host: novu-api-dev.ananta.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: novu-api-dev-tls
        hosts:
          - novu-api-dev.ananta.local

web:
  replicaCount: 1
  ingress:
    hosts:
      - host: novu-dev.ananta.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: novu-web-dev-tls
        hosts:
          - novu-dev.ananta.local

worker:
  replicaCount: 1
  autoscaling:
    enabled: false

ws:
  replicaCount: 1

mongodb:
  host: mongodb-dev.database-system.svc.cluster.local

redis:
  host: redis-dev.cache-system.svc.cluster.local

podDisruptionBudget:
  enabled: false
