replicaCount: 1
autoscaling:
  enabled: false
ingress:
  hosts:
    - host: orchestrator-dev.ananta.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: orchestrator-service-dev-tls
      hosts:
        - orchestrator-dev.ananta.local
configMap:
  LOG_LEVEL: debug
  NODE_ENV: development
podDisruptionBudget:
  enabled: false
