replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
autoscaling:
  minReplicas: 3
  maxReplicas: 20
ingress:
  hosts:
    - host: middleware.ananta.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: middleware-api-prod-tls
      hosts:
        - middleware.ananta.io
configMap:
  LOG_LEVEL: warn
podDisruptionBudget:
  minAvailable: 2
